### ISSUE TITLE
Drop system tests with lettuce

### ISSUE THREAD

**Issue by PatriotRossii** [knatten/cppquiz#280]
lettuce has not been updated for a very long time, and the latest version it supports is [python 2.7](https://github.com/gabrielfalcao/lettuce/commit/fb0f24f7c53f1e6694054c2e5bfcd742d8e7f3d4), which is incompatible with python 3.6 or python 3.7 from our requirements

Just an attempt to execute `./run_lettuce` gives an error:

```
  File "/home/eoanermine/cppquiz/venv/lib/python3.10/site-packages/lettuce/__init__.py", line 179
    print "Error loading step definitions:\n", e
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
```

**Comment by PatriotRossii** [comment]
https://stackoverflow.com/a/39527043

**Comment by PatriotRossii** [comment]
There is also troubles with [lettuce fork that pretends to support python 3](https://github.com/sgpy/lettuce):

```
(venv) eoanermine@eoanermine:~/cppquiz$ ./run_lettuce 
/home/eoanermine/cppquiz/venv/lib/python3.10/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
Traceback (most recent call last):
  File "/home/eoanermine/cppquiz/venv/lib/python3.10/site-packages/lettuce/django/server.py", line 63, in <module>
    from django.utils.six.moves import socketserver
ModuleNotFoundError: No module named 'django.utils.six'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eoanermine/cppquiz/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/eoanermine/cppquiz/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/home/eoanermine/cppquiz/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/eoanermine/cppquiz/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 279, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/eoanermine/cppquiz/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 48, in load_command_class
    module = import_module("%s.management.commands.%s" % (app_name, name))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/eoanermine/cppquiz/venv/lib/python3.10/site-packages/lettuce/django/management/commands/harvest.py", line 34, in <module>
    from lettuce.django.server import LettuceServerException
  File "/home/eoanermine/cppquiz/venv/lib/python3.10/site-packages/lettuce/django/server.py", line 65, in <module>
    import SocketServer as socketserver
ModuleNotFoundError: No module named 'SocketServer'
```

**Comment by knatten** [comment]
Yeah these have not been maintained since at least 2016. It's mentioned in the README, but nice to get an issue for it too. I haven't worked in web development since 2007 or so, so I have no idea what's good these days! :D 

I would also be fine with skipping the BDD style tests entirely and just convert the tests in `quiz/features` to regular python system tests with splinter. Maybe that's actually better anyway, since it will be more familiar to regular Python devs, and there's little value to the BDD style anyway when everyone involved is a programmer.

**Comment by tocic** [comment]
There is also an alternative called [`behave`](https://github.com/behave/behave) which seems to be well-maintained.

[Differences from `lettuce`](https://behave.readthedocs.io/en/stable/comparison.html#lettuce).
[Integration with Django](https://behave.readthedocs.io/en/stable/usecase_django.html).

**Comment by knatten** [comment]
Personally I would prefer to just convert them to regular python tests, I don't think we need a BDD-framework. The reason I went BDD back then was just as an excuse to try a BDD framework for the first time.

But if anyone is keen on trying out behave or aloe or something, I'm fine with that too. The only requirement from my side is that it's well maintained, and doesn't put any unnecessary limitations on what we're able to test.
